{{- if .Values.service.ports }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $value := .Values.service.ports }}
    - name: {{ $value.name }}
      targetPort: {{ $value.internalPort }}
      port: {{ $value.externalPort }}
      protocol: {{ $value.protocol }}
    {{- end }}
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
{{- end }}
