apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "service.fullname" . }}
spec:
  gateways:
  - {{ .Values.istio.gateways }}
  hosts:
  - {{ .Values.istio.host.url }}
  {{- if .Values.service.ports }}
  http:
  - route:
    {{- range $value := .Values.service.ports }}
    - destination:
        host: {{ include "service.fullname" $ }}
        port:
          number: {{ $value.externalPort }}
    {{- end }}
  {{- end }}
